name: Cron Pins (Failures)

on:
  schedule:
    - cron: '0 16 * * *'

jobs:
  update:
    name: Update pin statuses and size for pins with PinError status
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ['staging', 'production']
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run job
        env:
          DEBUG: '*'
          ENV: ${{ matrix.env }}
          FAUNA_KEY: ${{ secrets.PROD_FAUNA_KEY }}
          STAGING_FAUNA_KEY: ${{ secrets.STAGING_FAUNA_KEY }}
          CLUSTER_API_URL: ${{ secrets.CLUSTER_API_URL }}
          CLUSTER_BASIC_AUTH_TOKEN: ${{ secrets.CLUSTER_BASIC_AUTH_TOKEN }}
          CLUSTER_IPFS_PROXY_API_URL: ${{ secrets.CLUSTER_IPFS_PROXY_API_URL }}
          CLUSTER_IPFS_PROXY_BASIC_AUTH_TOKEN: ${{ secrets.CLUSTER_IPFS_PROXY_BASIC_AUTH_TOKEN }}
        run: npm run start:pins:failures -w packages/cron
